-- Instalación nueva; aplicar una sola vez en un proyecto dedicado.
BEGIN;
CREATE TABLE IF NOT EXISTS usuarios (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario                VARCHAR(50)                                    NOT NULL UNIQUE,
  password               VARCHAR(255)                                   NOT NULL,
  nombre                 VARCHAR(50)                                    DEFAULT NULL,
  apellido               VARCHAR(50)                                    DEFAULT NULL,
  dni                    VARCHAR(20)                                    UNIQUE,
  activo                 SMALLINT NOT NULL DEFAULT 1 CHECK (activo IN (0, 1)),
  rango                  TEXT                 NOT NULL,
  permiso                TEXT            NOT NULL,
  debe_cambiar_password  SMALLINT                                     NOT NULL DEFAULT 1,
  email_usuario          VARCHAR(150)                                   NOT NULL DEFAULT '',
  email_familiar         VARCHAR(150)                                   NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cursos (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anio      INT                                NOT NULL,
  division  VARCHAR(5)                         NOT NULL,
  turno     TEXT     NOT NULL
);

CREATE TABLE IF NOT EXISTS materias (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre  VARCHAR(100) NOT NULL
);

-- ── Tablas de relación (dependen de las anteriores) ─────────────────

CREATE TABLE IF NOT EXISTS curso_materia (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_id   INT          NOT NULL,
  materia_id INT          NOT NULL,
  dias       VARCHAR(50)  DEFAULT NULL,
  horario    VARCHAR(50)  DEFAULT NULL,
  UNIQUE (curso_id, materia_id),
  CONSTRAINT fk_cm_curso   FOREIGN KEY (curso_id)   REFERENCES cursos(id)   ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_cm_materia FOREIGN KEY (materia_id) REFERENCES materias(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS alumno_curso (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id INT NOT NULL,
  curso_id  INT NOT NULL,
  UNIQUE (alumno_id, curso_id),
  CONSTRAINT fk_ac_alumno FOREIGN KEY (alumno_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ac_curso  FOREIGN KEY (curso_id)  REFERENCES cursos(id)   ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS profesor_materia (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profesor_id      INT NOT NULL,
  curso_materia_id INT NOT NULL,
  UNIQUE (profesor_id, curso_materia_id),
  CONSTRAINT fk_pm_profesor      FOREIGN KEY (profesor_id)      REFERENCES usuarios(id)      ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pm_curso_materia FOREIGN KEY (curso_materia_id) REFERENCES curso_materia(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS preceptor_curso (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  preceptor_id INT NOT NULL,
  curso_id     INT NOT NULL,
  UNIQUE (preceptor_id, curso_id),
  CONSTRAINT fk_pc_preceptor FOREIGN KEY (preceptor_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pc_curso     FOREIGN KEY (curso_id)     REFERENCES cursos(id)   ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS evaluaciones (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curso_materia_id     INT          NOT NULL,
  tipo                 TEXT DEFAULT NULL,
  descripcion          VARCHAR(500) DEFAULT NULL,
  fecha                DATE         DEFAULT NULL,
  bimestre             INT          DEFAULT NULL,
  cierre               INT          DEFAULT NULL,
  es_acumulativo       SMALLINT   NOT NULL DEFAULT 0,
  evaluacion_origen_id INT          DEFAULT NULL,
  CONSTRAINT fk_ev_curso_materia FOREIGN KEY (curso_materia_id)     REFERENCES curso_materia(id) ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_ev_origen        FOREIGN KEY (evaluacion_origen_id) REFERENCES evaluaciones(id)  ON DELETE CASCADE  ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS notas (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluacion_id INT          NOT NULL,
  alumno_id     INT          NOT NULL,
  nota          DECIMAL(4,2) NOT NULL,
  UNIQUE (evaluacion_id, alumno_id),
  CONSTRAINT fk_nota_evaluacion FOREIGN KEY (evaluacion_id) REFERENCES evaluaciones(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_nota_alumno     FOREIGN KEY (alumno_id)     REFERENCES usuarios(id)     ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE usuarios ADD CONSTRAINT usuarios_rango_check CHECK (rango IN ('profesor','alumno','regente','preceptor','secretario'));
ALTER TABLE usuarios ADD CONSTRAINT usuarios_permiso_check CHECK (permiso IN ('lectura','escritura','ambos'));
ALTER TABLE usuarios ADD CONSTRAINT usuarios_password_change_check CHECK (debe_cambiar_password IN (0,1));
ALTER TABLE cursos ADD CONSTRAINT cursos_turno_check CHECK (turno IN ('manana','tarde','noche'));
CREATE INDEX ON alumno_curso (curso_id);
CREATE INDEX ON curso_materia (materia_id);
CREATE INDEX ON profesor_materia (curso_materia_id);
CREATE INDEX ON preceptor_curso (curso_id);
CREATE INDEX ON evaluaciones (curso_materia_id);
CREATE INDEX ON evaluaciones (evaluacion_origen_id);
CREATE INDEX ON notas (alumno_id);
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE materias ENABLE ROW LEVEL SECURITY;
ALTER TABLE curso_materia ENABLE ROW LEVEL SECURITY;
ALTER TABLE alumno_curso ENABLE ROW LEVEL SECURITY;
ALTER TABLE profesor_materia ENABLE ROW LEVEL SECURITY;
ALTER TABLE preceptor_curso ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE notas ENABLE ROW LEVEL SECURITY;

-- Sin políticas públicas: las credenciales del servidor son las únicas con acceso.
-- La aplicación conserva su autenticación JWT y autorización por rol.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
  END IF;
END $$;

COMMIT;
